### ISSUE TITLE
Fabric example is not working

### ISSUE THREAD

**Issue by tino** [theskumar/python-dotenv#14]
```
fab config:set,hello=world
Executing task 'config'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 387, in execute
    multiprocessing
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
TypeError: config() got an unexpected keyword argument 'hello'
```
fabric parses the `hello=world` and passes it to the config task as a keyword argument. I had to use:

```
@task
def config(action=None, **kwargs):
    """Manage project configuration via .env

    e.g: fab config:set,<key>=<value>
         fab config:get,<key>
         fab config:unset,<key>
         fab config:list
    """
    if len(kwargs):
        k, v = list(kwargs.items())[0]
        if v:
            key_value = "{}={}".format(k, v)
        else:
            key_value = k
    else:
        key_value = None
    command = dotenv.get_cli_string(env.dotenv_path, action, key_value)
    with environment():
        run(command)
```

But then fab `config:unset,hello` does not work anymore...

**Comment by theskumar** [comment]
Seems like the bug got introduced during 0.2.0 release. I would suggest follow the guide from 0.5.0 release https://github.com/theskumar/python-dotenv/tree/v0.1.5#setting-config-on-remote-servers i'll have it fixed in next release.

**Comment by theskumar** [comment]
I've release a v0.3.0 addressing the fixes. Have a look at the latest Readme https://github.com/theskumar/python-dotenv#setting-config-on-remote-servers

**Comment by tino** [comment]
Cool, thanks!
