### ISSUE TITLE
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

### ISSUE THREAD

**Issue by denojike** [theskumar/python-dotenv#167]
C:\MyPythonScripts>pip3 install pyzmail
Collecting pyzmail
  Using cached https://files.pythonhosted.org/packages/23/9a/c8709821fa15cec44f825fba884284b261a06d8a0033a16f4c35470eb26a/pyzmail-1.0.3.tar.gz
Collecting distribute (from pyzmail)
  Using cached https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\DENCOT~1\AppData\Local\Temp\pip-install-z7dyk64h\distribute\setuptools\__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "C:\Users\DENCOT~1\AppData\Local\Temp\pip-install-z7dyk64h\distribute\setuptools\extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "C:\Users\DENCOT~1\AppData\Local\Temp\pip-install-z7dyk64h\distribute\setuptools\dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "C:\Users\DENCOT~1\AppData\Local\Temp\pip-install-z7dyk64h\distribute\setuptools\command\__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "C:\Users\DENCOT~1\AppData\Local\Temp\pip-install-z7dyk64h\distribute\setuptools\command\install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "C:\Users\DENCOT~1\AppData\Local\Temp\pip-install-z7dyk64h\distribute\pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\DENCOT~1\AppData\Local\Temp\pip-install-z7dyk64h\distribute\

Hello guys! How do I solve this problem? Am trying to install pyzmail and got this.

C:\MyPythonScripts>python --version
Python 3.7.0

C:\MyPythonScripts>pip --version
pip 19.0.1 from c:\python\lib\site-packages\pip (python 3.7)

**Comment by phildini** [comment]
I am also having this error.

**Comment by mukiblejlok** [comment]
I have noticed the same error, but then I've realised I typed `pip install dotenv`.
However, to install the right module it should be `pip install python-dotenv` as in the name of this repository.
Maybe it is the same issue in your case.

**Comment by cryptopinnacle** [comment]
Thank you guys.

**Comment by bbc2** [comment]
I'm closing this since the problem seems to be solved and doesn't come from python-dotenv itself.
