### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'True'

### ISSUE THREAD

**Issue by Thagana** [theskumar/python-dotenv#202]
When I try to set `DEBUG=True `and load it using `DEBUG=os.getenv("DEBUG")` the the below error

`
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from application import app
  File "C:\Users\kiddies\application\__init__.py", line 30, in <module>
    mail = Mail(app)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 539, in __init__
    self.state = self.init_app(app)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 566, in init_app
    state = self.init_mail(app.config, app.debug, app.testing)
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 552, in init_mail
    int(config.get('MAIL_DEBUG', debug)),
ValueError: invalid literal for int() with base 10: 'True'

`
When I change from `DEBUG=os.getenv("DEBUG")` to `DEBUG=True` the error goes away.

**Comment by theskumar** [comment]
@Thagana getenv will always return a string you need to convert that string into boolean
