### ISSUE TITLE
Unable to install in ascii environments

### ISSUE THREAD

**Issue by AbdealiJK** [theskumar/python-dotenv#214]
When I try to install from source in a environment where locale is not set, it gives an error:
```
  Using cached https://files.pythonhosted.org/packages/29/72/c3f4a251fd2dfcacddfb2e15e069e8345c0cde38ac0a6da8be5081de35d2/python-dotenv-0.10.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zrgx11n2/python-dotenv/setup.py", line 5, in <module>
        long_description = f.read()
      File "/opt/miniconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1544: ordinal not in range(128)
```

This is because of this part in the README which contains non-ascii text:
```
.
├── .env
└── settings.py
```

It would be beneficial to change this part to:
```
.
|-- .env
+-- settings.py
```

**Comment by dbsanfte** [comment]
I have just hit this as well. We are unable to install due to these unicode characters in the file.

**Comment by dbsanfte** [comment]
I was able to fix this by setting:

`LC_ALL=C.UTF-8`

...before invoking `pip install`. Works now.
