### ISSUE TITLE
Cannot load env variables into settings.py in django 2.2

### ISSUE THREAD

**Issue by rajkumartreads** [theskumar/python-dotenv#217]
Stack: Python 3.7.5 + Django 2.2.8 + mod_wsgi 4.7.0 + httpd + CentOS 7.6

The .env file is located in the folder which contains settings.py

Sharing my django project code:

**wsgi.py**
```
import os
from django.core.wsgi import get_wsgi_application
from dotenv import load_dotenv

load_dotenv()

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'xxxx.settings')
application = get_wsgi_application()
```

**manage.py**
```
import os
import sys
from dotenv import load_dotenv

load_dotenv()

def main():
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'xxxx.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
```

**settings.py**

```
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRET_KEY = os.getenv('SECRET_KEY')
.
.
.

```

I am getting the following error in *httpd/logs/error_log*

```
mod_wsgi (pid=1091): Failed to exec Python script file '/srv/django/xxxx/xxxx/xxxx/wsgi.py'.

mod_wsgi (pid=1091): Exception occurred processing WSGI script '/srv/django/xxxx/xxxx/xxxx/wsgi.py'.

Traceback (most recent call last):
File "/srv/django/xxxx/xxxx/xxxx/wsgi.py", line 19, in <module>
   application = get_wsgi_application()
.
.
.
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

```
The env loading works good in my development environment. But throws an error in production when working with httpd. I ensured that the permissions are set right.
What am I missing?

**Comment by xarpy** [comment]
Something similar happened to me, which solved part of the problem was using the `find_dotenv () `function. 
**My example:**

```
"""
Django settings for new_project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import logging
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import find_dotenv, load_dotenv

# TODO: Create new function or method to get locate path env.
# env_path = Path('core/.env') #don't work
# load_dotenv(dotenv_path=env_path) #don't work

load_dotenv(find_dotenv())

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
# See too https://docs.djangoproject.com/en/2.2/ref/settings/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG = os.getenv('DEBUG')
DEBUG = False

ALLOWED_HOSTS = os.getenv('HOSTS')

APPEND_SLASH = True
```

**My .env file:**

```
SECRET_KEY = '12345'
DEBUG = "False"
LOG = '/var/log/teste_project.log'
LOG_REQUESTS = '/var/log/teste_projec_requestt.log'
DATABASE_URL = 'postgres://user:12345@localhost:5432/database'
HOSTS=['*']

```
It's worked, however some variables cannot be detected as in the case of the variable called **DEBUG** and python-dotenv [cli] cannot find the file even inside the project folder if it uses the `find_dotenv () `function.

**My specs:**
_Project requirements_
```
dj-database-url==0.5.0    
Django==2.2.7    
django-debug-toolbar==2.0      
django-extensions==2.2.1      
djangorestframework==3.10.3   
python-dotenv==0.10.3
gunicorn==20.0.0
```
_Stack_
**python** 3.7.5 | **nginx** 1.17

**Comment by handhikadj** [comment]
@xarpy I've put nice emojis cause it works like a charm. Never thought there is a `find_dotenv` function. thank you.

**Comment by Ankitajain-kiwi** [comment]
hello, in my django project there is one error occur

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    main()
  File "manage.py", line 16, in main
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', os.getenv('SETTINGS'))
  File "/usr/lib/python3.6/os.py", line 706, in setdefault
    self[key] = value
  File "/usr/lib/python3.6/os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "/usr/lib/python3.6/os.py", line 744, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

Anybody help me

**Comment by jabz113** [comment]
Instead of SECRET_KEY = os.getenv('SECRET_KEY'), I used SECRET_KEY = str(os.getenv('SECRET_KEY')). This solved my problem.
