### ISSUE TITLE
python-dotenv fails to install on linux/ubuntu 

### ISSUE THREAD

**Issue by struegamer** [theskumar/python-dotenv#227]
HI,

encountered this issue when upgrading python-dotenv (which is pulled in as indirect dep from another lib):

```
       cwd: /tmp/pip-install-5x4oysqm/python-dotenv
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/opt/jenkins/9ffc0e42/workspace/kend_libs_lib-djangoutils_master/.tox/.env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/opt/jenkins/9ffc0e42/workspace/kend_libs_lib-djangoutils_master/.tox/.env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/jenkins/9ffc0e42/workspace/kend_libs_lib-djangoutils_master/.tox/.env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-pt2z8cq9/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-pt2z8cq9/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-pt2z8cq9/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-pt2z8cq9/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 13, in <module>
      long_description = read_files(['README.md', 'CHANGELOG.md'])
    File "setup.py", line 9, in read_files
      data.append(f.read())
    File "/opt/jenkins/9ffc0e42/workspace/kend_libs_lib-djangoutils_master/.tox/.env/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2589: ordinal not in range(128)```

This happens on linux/ubuntu 18.04 LTS

while installing the same package on mac os mojave works without issues.

Here is a longer output of a clean pip3 -vvvv install python-dotenv (0.10.5)

```Collecting python-dotenv
  1 location(s) to search for versions of python-dotenv:
  * https://pypi.python.org/simple/python-dotenv/
  Getting page https://pypi.python.org/simple/python-dotenv/
  Looking up "https://pypi.python.org/simple/python-dotenv/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /simple/python-dotenv/ HTTP/1.1" 301 122
  Updating cache with response from "https://pypi.python.org/simple/python-dotenv/"
  Caching permanant redirect
  Looking up "https://pypi.org/simple/python-dotenv/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/python-dotenv/ HTTP/1.1" 200 5004
  Updating cache with response from "https://pypi.org/simple/python-dotenv/"
  Caching due to etag
  Analyzing links from page https://pypi.org/simple/python-dotenv/
    Found link https://files.pythonhosted.org/packages/ad/3b/16a207ced20a1be0cc2ec5a53ab68ce1976ad643fe7f135d3addd763abf0/python-dotenv-0.1.0.tar.gz#sha256=26156022355d4457bc9062bcead7fde4824623d4463488b623bdd5ce912462fa (from https://pypi.org/simple/python-dotenv/), version: 0.1.0
    Found link https://files.pythonhosted.org/packages/e6/95/e9239c25d2c06c4a262360375d4e0c61b243d1c763d647137aca4d7df9fe/python-dotenv-0.1.2.tar.gz#sha256=aaefda0e975b702374f7c86edcf948590bd4f47737b33027de1bc72afbed745b (from https://pypi.org/simple/python-dotenv/), version: 0.1.2
    Found link https://files.pythonhosted.org/packages/9c/b8/b9c1dbc7fec4ddf85d1c5aed117e8a8393315378ad2100147304ec610c89/python_dotenv-0.1.2-py2.py3-none-any.whl#sha256=b2c451a7127d1ae2b2d5d5977c10f3e0c4892b4954ddd62fe3d9714bf12a2cfc (from https://pypi.org/simple/python-dotenv/), version: 0.1.2
    Found link https://files.pythonhosted.org/packages/9e/42/1e776bea4a00ff3712e0ed6b3a265e11e8b03948ec75d17796d1b2bde9fc/python-dotenv-0.1.3.tar.gz#sha256=31dea6e0190560ee2aa739fbff89e384673dec15f3b7125d9f7862563712d85c (from https://pypi.org/simple/python-dotenv/), version: 0.1.3
    Found link https://files.pythonhosted.org/packages/0d/c5/a74b5635785f82abd0a74febe89d904cd077b00337e89866ab83a21a6ca7/python_dotenv-0.1.3-py2.py3-none-any.whl#sha256=69e34c2a5b3637ad31e2988883812425c6102a653b1f296412326829265bf45b (from https://pypi.org/simple/python-dotenv/), version: 0.1.3
    Found link https://files.pythonhosted.org/packages/fd/68/c4e50632f14ad685779b426e4e4290f35315ef15bbef44faf81a2cfffc9b/python-dotenv-0.1.5.tar.gz#sha256=bf25afea51b7a7372c02acfbc0a7266b112ea60feba0d12c594ac4a91ea3404d (from https://pypi.org/simple/python-dotenv/), version: 0.1.5
    Found link https://files.pythonhosted.org/packages/41/cb/25e0b21f7492e854f5807133674440da32bcdb571f5588a0c8d70d87c248/python_dotenv-0.1.5-py2.py3-none-any.whl#sha256=ec818766adfe5a4d51d719a76936a17044b8279e6bfefb5567e341122c860c3d (from https://pypi.org/simple/python-dotenv/), version: 0.1.5
    Found link https://files.pythonhosted.org/packages/d1/2f/25a275868f3efd92a0009b906b9528317f3fa1689ce129ead705cc31e3e4/python-dotenv-0.2.0.tar.gz#sha256=88f1d4dc6586bed44d32361ee9866e23503fc93ebc80979d3bbca3fdace56716 (from https://pypi.org/simple/python-dotenv/), version: 0.2.0
    Found link https://files.pythonhosted.org/packages/8e/2c/435a76de0be9f187ddb6afb183eb09e4f787d02f0018e344ddaf8fb9ae64/python_dotenv-0.2.0-py2.py3-none-any.whl#sha256=f3e812c08a17002026934c994682e79564ea74c45cbfe11fdcfd3eab247113b1 (from https://pypi.org/simple/python-dotenv/), version: 0.2.0
    Found link https://files.pythonhosted.org/packages/87/39/3c784313ad92232f8ed971392f48a6274600f9d1453cdb4b8c745aa6f2e5/python-dotenv-0.3.0.tar.gz#sha256=dfef9eb4bfeecd822abbb355fd898d840cf31359664595a279f02fd048a1d7ae (from https://pypi.org/simple/python-dotenv/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/d4/1b/4fda26f911aba18fb1daea80c1fca3e4cc59f401d8ec0ab4359528930018/python_dotenv-0.3.0-py2.py3-none-any.whl#sha256=fa950d6b8d3314ade3ea2d4e0bb7425af666e297f34d8d94fa5c2df42d78a4d2 (from https://pypi.org/simple/python-dotenv/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/af/e1/3db0aad1cc058f69f9231778d7b3d249efc2e63cf4e5e8d40e1ae26a0dd0/python-dotenv-0.4.0.tar.gz#sha256=e761c79d90d661806c0dd760271352cce028c58404f0c68fc9a1dcea1566f291 (from https://pypi.org/simple/python-dotenv/), version: 0.4.0
    Found link https://files.pythonhosted.org/packages/1d/a6/d5487df8278db3adfe9c7588d36934b4a40e783f7c2ab6ece5256d40ec97/python_dotenv-0.4.0-py2.py3-none-any.whl#sha256=fb696a13f418bcabfca32216bd4f44fe8b288272cc4dce1e63d4d70f90d3373e (from https://pypi.org/simple/python-dotenv/), version: 0.4.0
    Found link https://files.pythonhosted.org/packages/62/76/b070efa8de2ac92fe81ae0102d9a118df8c8287209ed0b798e75058d4268/python-dotenv-0.5.0.tar.gz#sha256=b959a4f56c9159a4899ac366fb10b51528d1822a2b8c18093bb001fbc784e64b (from https://pypi.org/simple/python-dotenv/), version: 0.5.0
    Found link https://files.pythonhosted.org/packages/a8/7f/93686888086bb2aea82b1369d54e286a5a3d500f09bee144be5d47bc62e7/python_dotenv-0.5.0-py2.py3-none-any.whl#sha256=9d729f21c0b0fd1c6425b52cb07e2106cde02f9c16912433993b5d9cd626328a (from https://pypi.org/simple/python-dotenv/), version: 0.5.0
    Found link https://files.pythonhosted.org/packages/f1/ef/8eea27f2f50e25f4d4c7cc651ace16333f78cc01366e1a09c78e94aef07b/python-dotenv-0.5.1.tar.gz#sha256=d139a406b7dd0ecc161f0b9cd1620de93bda026fe3c776bd1216414898704c8d (from https://pypi.org/simple/python-dotenv/), version: 0.5.1
    Found link https://files.pythonhosted.org/packages/3b/5b/0e8ed9c39d3675fca02020713c4d12e1df0e79194a66aabcec74200552c7/python_dotenv-0.5.1-py2.py3-none-any.whl#sha256=46d58321d745d9d6f23e802b51dec8c2320a43c1ef0423671ed2a084bbd77eff (from https://pypi.org/simple/python-dotenv/), version: 0.5.1
    Found link https://files.pythonhosted.org/packages/25/5d/411d063f7e0219c4400a6ab3afb675da6f3fca71bc93852405404e409d42/python-dotenv-0.6.0.tar.gz#sha256=7e371d6ecc0019535f350e8ea413fbb226a9f8c16c80339e347664f7a0613202 (from https://pypi.org/simple/python-dotenv/), version: 0.6.0
    Found link https://files.pythonhosted.org/packages/25/db/213723b08b954618cd893895dad786b6035b4085549a69200f0309eed2f6/python_dotenv-0.6.0-py2.py3-none-any.whl#sha256=19f059bdfb76d98b468c808a76c2d9da0446c284b79c84a434fafee9333302bf (from https://pypi.org/simple/python-dotenv/), version: 0.6.0
    Found link https://files.pythonhosted.org/packages/7a/35/4a85365fd73dbc823f6a2a2cffd843325a8c32d46140b54342d53cfb0620/python-dotenv-0.6.1.tar.gz#sha256=bd8ed28f7365de0cbd0a28bf77bc5171444e7031853172749b5cea6c85a3928f (from https://pypi.org/simple/python-dotenv/), version: 0.6.1
    Found link https://files.pythonhosted.org/packages/19/fc/95fe4cc409f13aa9e6d7e8ccc99bb77d76ebb58940685197b1314912b34f/python_dotenv-0.6.1-py2.py3-none-any.whl#sha256=7350c0a2d510886a36de762442bf306eb45d943dd7ca2a245a1748e89a7c9686 (from https://pypi.org/simple/python-dotenv/), version: 0.6.1
    Found link https://files.pythonhosted.org/packages/c9/33/2077c2a7e81ad2a262f27137262aa00da183ec20d648e0c5fdff6b31bc66/python-dotenv-0.6.2.tar.gz#sha256=8c0ca9e8494a64e96daee2db36af9b14413a8e2b48ab4502c8ce460d2420639c (from https://pypi.org/simple/python-dotenv/), version: 0.6.2
    Found link https://files.pythonhosted.org/packages/21/cb/93addfb1f9e72487c4395ac862765cd906a889f977fd549d663e44e65001/python-dotenv-0.6.3.tar.gz#sha256=704b6b0f09ab22842831fd87b4ef05c36a3d5288411fc7375ca489f5fc574e7b (from https://pypi.org/simple/python-dotenv/), version: 0.6.3
    Found link https://files.pythonhosted.org/packages/4c/0d/cfaacfa18609c7c3488a7f3a2f119d37aeb96a7299de01ec1debf4329acf/python_dotenv-0.6.3-py2.py3-none-any.whl#sha256=e47a575237f2dc96f29a275f381817dab3dd71921c604d5b9d0c51d836541393 (from https://pypi.org/simple/python-dotenv/), version: 0.6.3
    Found link https://files.pythonhosted.org/packages/9e/c1/43f80f629f363be1b7b33f66cfc8fe098eb5065c9dcc4e5ce4cabba176ed/python-dotenv-0.6.4.tar.gz#sha256=db38f9e42a7bb53c68d0aa3ce97c18b62250dc21b64896be27246dfb96315d55 (from https://pypi.org/simple/python-dotenv/), version: 0.6.4
    Found link https://files.pythonhosted.org/packages/0c/9d/b23992f7d2dc8cde9b8f202f00cfd7f81c2c91ba4c029bd0c6ea409f2b28/python_dotenv-0.6.4-py2.py3-none-any.whl#sha256=bac21323df7ab51765948442392872e0ad89cc5c9122ab7f41bd8ad689fc7c72 (from https://pypi.org/simple/python-dotenv/), version: 0.6.4
    Found link https://files.pythonhosted.org/packages/10/b8/36604f1ea03db8303908f892f73008f61ac20025e52a7ab87e40f622ec6a/python-dotenv-0.6.5.tar.gz#sha256=29ea91ec8eb1f11d3d8f1b90efec1fb3ce6218ab322d8f58cb854290ad760531 (from https://pypi.org/simple/python-dotenv/), version: 0.6.5
    Found link https://files.pythonhosted.org/packages/da/a8/ed17a2786ca77b5af6c1998836d800745b766c20685a922d46b68bf8d547/python_dotenv-0.6.5-py2.py3-none-any.whl#sha256=6e0ca7970131af5f892cab7ac0bc8f0580e380d27c070c297c7fc65921afb2ce (from https://pypi.org/simple/python-dotenv/), version: 0.6.5
    Found link https://files.pythonhosted.org/packages/b6/96/88d715689a354103fb23191d1c0da6d462e8488759df893d7b6df6419fb2/python-dotenv-0.7.0.tar.gz#sha256=5728968fd9ba90db0eb533c92f710a5b1e3eb7bd93976fb94fad4c3c27392676 (from https://pypi.org/simple/python-dotenv/), version: 0.7.0
    Found link https://files.pythonhosted.org/packages/f8/46/d35bcdcb17f2419ad9d43df6ca14c39d2dc85b450878090d75c51d1296dc/python_dotenv-0.7.0-py2.py3-none-any.whl#sha256=deea57d0223ddad3689a9f0af512334676598eebbe03fe875fa65885e485be74 (from https://pypi.org/simple/python-dotenv/), version: 0.7.0
    Found link https://files.pythonhosted.org/packages/27/15/643b94dc9addf26920d829857c1ca987da0a9b7a03df1b54535f0f0bb46d/python-dotenv-0.7.1.tar.gz#sha256=45e927c34204c90f5faa35ea8709b894f6b1a7712d77eb50940601068040993b (from https://pypi.org/simple/python-dotenv/), version: 0.7.1
    Found link https://files.pythonhosted.org/packages/68/90/24d14dba4e26e20e83225df21a55b701488df88b77700c55422f97bc1be0/python_dotenv-0.7.1-py2.py3-none-any.whl#sha256=dc7940052cfe170e881aea40feb4ea7776e6a97170ed038fd2ee7e26e47585f2 (from https://pypi.org/simple/python-dotenv/), version: 0.7.1
    Found link https://files.pythonhosted.org/packages/fb/1d/762f72921b806045a260b67f1d0c8be3b990dc771d8d4f120fa7dce80540/python-dotenv-0.8.0.tar.gz#sha256=2bfeb2ce1b5d1ce46ecdce5c9d55e4976ca403fdcc251b4870e5c0647d0dce67 (from https://pypi.org/simple/python-dotenv/), version: 0.8.0
    Found link https://files.pythonhosted.org/packages/7e/10/3abb862f05f841f109036f84e851468abac76eb1ba53de2bc3c4baa3cb5b/python_dotenv-0.8.0-py2.py3-none-any.whl#sha256=2a0073a6f7a10156de2ab7d8c2399b5e86ac61786206f6e1b4a1fcad92fa2dd1 (from https://pypi.org/simple/python-dotenv/), version: 0.8.0
    Found link https://files.pythonhosted.org/packages/d7/38/ff92a17d18390f22eef2a3dce0f3b0f8f5af0431185d749d7ac52de21eea/python-dotenv-0.8.1.tar.gz#sha256=943f52f61519e7f74d0ddaf48cb639700fcbb049edc541b65b886951dde6b37c (from https://pypi.org/simple/python-dotenv/), version: 0.8.1
    Found link https://files.pythonhosted.org/packages/44/e0/06afdb7259bbe3a62c5ffc9920b7534afbae25a32704c28825caa6dc1208/python_dotenv-0.8.1-py2.py3-none-any.whl#sha256=04ce66e8570056702a4339a4a8d8e91b814a2948536a6cc3b29544e8704f9bab (from https://pypi.org/simple/python-dotenv/), version: 0.8.1
    Found link https://files.pythonhosted.org/packages/23/6c/1b6558c7d666736ad52a12ec707e18e2d409baa61a6425ed9b154c829485/python-dotenv-0.8.2.tar.gz#sha256=509736185257111613009974e666568a1b031b028b61b500ef1ab4ee780089d5 (from https://pypi.org/simple/python-dotenv/), version: 0.8.2
    Found link https://files.pythonhosted.org/packages/85/9f/b76a51bb851fa25f7a162a16297f4473c67ec42dd55e4f7fc5b43913a606/python_dotenv-0.8.2-py2.py3-none-any.whl#sha256=4965ed170bf51c347a89820e8050655e9c25db3837db6602e906b6d850fad85c (from https://pypi.org/simple/python-dotenv/), version: 0.8.2
    Found link https://files.pythonhosted.org/packages/dc/8c/d38f2b3b2d9cdc3d94f39ad007c65ff88b752fc11a26b29ca1dea28597d9/python-dotenv-0.9.0.tar.gz#sha256=38f22d75f1180256e60c8b06aa06f5254479c1bf5947430c97e3d737d90e8731 (from https://pypi.org/simple/python-dotenv/), version: 0.9.0
    Found link https://files.pythonhosted.org/packages/b0/7e/00daf9870818a31fca9027635dad73a87be892616bb4a108e32cade8738c/python_dotenv-0.9.0-py2.py3-none-any.whl#sha256=52e8c56e7c362fe9082abc949ea5fed6993c3651e059df0d7c8e18883827d737 (from https://pypi.org/simple/python-dotenv/), version: 0.9.0
    Found link https://files.pythonhosted.org/packages/48/a3/36d63f471cc676cd8b7125fcd85efc022bc04e111db32c33cd80e63ec19b/python-dotenv-0.9.1.tar.gz#sha256=122290a38ece9fe4f162dc7c95cae3357b983505830a154d3c98ef7f6c6cea77 (from https://pypi.org/simple/python-dotenv/), version: 0.9.1
    Found link https://files.pythonhosted.org/packages/24/3d/977140bd94bfb160f98a5c02fdfbb72325130f12a325cf993182956e9d0e/python_dotenv-0.9.1-py2.py3-none-any.whl#sha256=4a205787bc829233de2a823aa328e44fd9996fedb954989a21f1fc67c13d7a77 (from https://pypi.org/simple/python-dotenv/), version: 0.9.1
    Found link https://files.pythonhosted.org/packages/8f/c0/0ada2151a76103377110cf5f0a4fcfd79284a3d2b6fbaf2a406d8536ede5/python-dotenv-0.10.0.tar.gz#sha256=4f3582904d08dac5ab4c9aa44cb17ce056c9a35e585cfda6183d80054d247307 (from https://pypi.org/simple/python-dotenv/), version: 0.10.0
    Found link https://files.pythonhosted.org/packages/5d/0a/07199c77b5054f5f3b6c3b167fd794ca3fd071f9640ce1af16497516f2df/python_dotenv-0.10.0-py2.py3-none-any.whl#sha256=cb8cd327109898c7725f76c5256a081e8a9efe72ebbf127f8d1221ceb7f38bf2 (from https://pypi.org/simple/python-dotenv/), version: 0.10.0
    Found link https://files.pythonhosted.org/packages/0f/fe/b0e23db9c6b7dc8c2b21b62990890c85441c95557be1f3f3d5a126ec3009/python-dotenv-0.10.1.tar.gz#sha256=c9b1ddd3cdbe75c7d462cb84674d87130f4b948f090f02c7d7144779afb99ae0 (from https://pypi.org/simple/python-dotenv/), version: 0.10.1
    Found link https://files.pythonhosted.org/packages/8c/14/501508b016e7b1ad0eb91bba581e66ad9bfc7c66fcacbb580eaf9bc38458/python_dotenv-0.10.1-py2.py3-none-any.whl#sha256=a84569d0e00d178bc5b957f7ff208bf49287cbf61857c31c258c4a91f571527b (from https://pypi.org/simple/python-dotenv/), version: 0.10.1
    Found link https://files.pythonhosted.org/packages/2d/f0/f89093378e5a7c028d7d618c9ce60a7853a1f36d46ff9e497ba03df102d5/python-dotenv-0.10.2.tar.gz#sha256=6640acd76e6cab84648e4fec16c9d19de6700971f9d91d045e7120622167bfda (from https://pypi.org/simple/python-dotenv/), version: 0.10.2
    Found link https://files.pythonhosted.org/packages/df/e2/8acf58886c3f013290eb2e17c912fd989d28a61759927be2a28e0f4c1687/python_dotenv-0.10.2-py2.py3-none-any.whl#sha256=156f218846bd90e0d537915545cde4a987947c2cecc628b50f9955fdde72534a (from https://pypi.org/simple/python-dotenv/), version: 0.10.2
    Found link https://files.pythonhosted.org/packages/29/72/c3f4a251fd2dfcacddfb2e15e069e8345c0cde38ac0a6da8be5081de35d2/python-dotenv-0.10.3.tar.gz#sha256=f157d71d5fec9d4bd5f51c82746b6344dffa680ee85217c123f4a0c8117c4544 (from https://pypi.org/simple/python-dotenv/), version: 0.10.3
    Found link https://files.pythonhosted.org/packages/57/c8/5b14d5cffe7bb06bedf9d66c4562bf90330d3d35e7f0266928c370d9dd6d/python_dotenv-0.10.3-py2.py3-none-any.whl#sha256=debd928b49dbc2bf68040566f55cdb3252458036464806f4094487244e2a4093 (from https://pypi.org/simple/python-dotenv/), version: 0.10.3
    Found link https://files.pythonhosted.org/packages/a5/89/2c00ccae62552e5deac08e66abb751b91ac3bb2e1a040e1a349510df1fee/python-dotenv-0.10.4.tar.gz#sha256=007f0bacef4093a7588c1ed0a3d746a59c04f9bac00f68aaa4e9c30c5fe9429b (from https://pypi.org/simple/python-dotenv/), version: 0.10.4
    Found link https://files.pythonhosted.org/packages/c7/0e/37725957ab14dd1b574be428f573000886d4ee6322c03201a43022a756c8/python_dotenv-0.10.4-py2.py3-none-any.whl#sha256=26a252f7931a448a78d3322d69b60e193d847a02fb96260de1d7b37aadcd46b3 (from https://pypi.org/simple/python-dotenv/), version: 0.10.4
    Found link https://files.pythonhosted.org/packages/65/16/43f00b087c7f3f20a8d8dc16d6f6e2eff4e662afcb31ec4a31535a5be244/python-dotenv-0.10.5.tar.gz#sha256=f254bfd0c970d64ccbb6c9ebef3667ab301a71473569c991253a481f1c98dddc (from https://pypi.org/simple/python-dotenv/), version: 0.10.5
  Using version 0.10.5 (newest of versions: 0.1.0, 0.1.2, 0.1.3, 0.1.5, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
  Looking up "https://files.pythonhosted.org/packages/65/16/43f00b087c7f3f20a8d8dc16d6f6e2eff4e662afcb31ec4a31535a5be244/python-dotenv-0.10.5.tar.gz" in the cache
  No cache entry available
  Starting new HTTPS connection (1): files.pythonhosted.org
  https://files.pythonhosted.org:443 "GET /packages/65/16/43f00b087c7f3f20a8d8dc16d6f6e2eff4e662afcb31ec4a31535a5be244/python-dotenv-0.10.5.tar.gz HTTP/1.1" 200 27837
  Downloading https://files.pythonhosted.org/packages/65/16/43f00b087c7f3f20a8d8dc16d6f6e2eff4e662afcb31ec4a31535a5be244/python-dotenv-0.10.5.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/65/16/43f00b087c7f3f20a8d8dc16d6f6e2eff4e662afcb31ec4a31535a5be244/python-dotenv-0.10.5.tar.gz#sha256=f254bfd0c970d64ccbb6c9ebef3667ab301a71473569c991253a481f1c98dddc (from https://pypi.org/simple/python-dotenv/)
  Updating cache with response from "https://files.pythonhosted.org/packages/65/16/43f00b087c7f3f20a8d8dc16d6f6e2eff4e662afcb31ec4a31535a5be244/python-dotenv-0.10.5.tar.gz"
  Caching due to etag
  Running setup.py (path:/tmp/pip-build-d0umo30w/python-dotenv/setup.py) egg_info for package python-dotenv
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d0umo30w/python-dotenv/setup.py", line 13, in <module>
        long_description = read_files(['README.md', 'CHANGELOG.md'])
      File "/tmp/pip-build-d0umo30w/python-dotenv/setup.py", line 9, in read_files
        data.append(f.read())
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2589: ordinal not in range(128)
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d0umo30w/python-dotenv/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d0umo30w/python-dotenv/```

python-dotenv 0.10.3 and 0.10.4 are installing without issues

**Comment by nat45928** [comment]
I'm also seeing this on on Ubuntu 18.04.3.

**Comment by struegamer** [comment]
See discussion on 
https://github.com/theskumar/python-dotenv/commit/3637b3e114b9a3084457594ccfa3cb3e6d3d4ee4

**Comment by bbc2** [comment]
I've uploaded a wheel for 0.10.5.  Does installing work now?

I've also fixed the CI so that wheels of future versions are always uploaded to PyPI (#228).

**Comment by and-semakin** [comment]
Because of uploaded wheel library hashes started to differ, it breaks Pipenv. I think better solution in such situations is to bump version and create another release, not to change existing :)

**Comment by bbc2** [comment]
I feel like Pipenv should know better than complain about a new file since the source distribution hasn't changed, but maybe I'm missing something.

Anyway, sorry for the disruption.  I've made sure that this won't happen again.

**Comment by struegamer** [comment]
It works again :) Thanks for the quick fix.
