### ISSUE TITLE
python-dotenv fails to install on macOS python 3.8

### ISSUE THREAD

**Issue by jeremypng** [theskumar/python-dotenv#268]
pip install fails with below output

```
(venv) localhost:test-project test$ pip install -r requirements.txt 
Requirement already satisfied: pynetbox in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (5.0.5)
Requirement already satisfied: dnacentersdk in ./venv/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.0.0)
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/test/Documents/test-project/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-install-e2vraf18/dotenv/setup.py'"'"'; __file__='"'"'/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-install-e2vraf18/dotenv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-pip-egg-info-1t1vef5k
         cwd: /private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-install-e2vraf18/dotenv/
    Complete output (52 lines):
    WARNING: The wheel package is not available.
        ERROR: Command errored out with exit status 1:
         command: /Users/test/Documents/test-project/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/setup.py'"'"'; __file__='"'"'/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-pip-egg-info-7uw20k6y
             cwd: /private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/
        Complete output (15 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/setuptools/__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/setuptools/extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/setuptools/dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/setuptools/command/__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/setuptools/command/install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-wheel-5u137z6b/distribute/pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    Traceback (most recent call last):
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/Cellar/python@3.8/3.8.4/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/test/Documents/test-project/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/tmp043jll3f', '--quiet', 'distribute']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/pip-install-e2vraf18/dotenv/setup.py", line 13, in <module>
        setup(name='dotenv',
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/test/Documents/test-project/venv/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/Users/test/Documents/test-project/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/80/5dkl_lsn4nb9bx57_chc4qtr0000gn/T/tmp043jll3f', '--quiet', 'distribute']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jeremypng** [comment]
python installed via homebrew:


```
(venv) localhost:test-project test$ python --version
Python 3.8.4
(venv) localhost:test-project test$ pip --version
pip 20.1.1 from /Users/test/Documents/test-project/venv/lib/python3.8/site-packages/pip (python 3.8)
(venv) localhost:test-project test$ 
```

**Comment by sanders41** [comment]
Do you get the same error if you don't use cache? `pip install -r requirements.txt --no-cache-dir`

**Comment by bbc2** [comment]
I agree, trying without cache might help.  This line in the output you posted looks surprising:

```
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
```

That version of Python-dotenv is very old.

**Comment by bbc2** [comment]
Wait a minute, that's not Python-dotenv you're trying to install, it's dotenv, another package.  Try `pip install python-dotenv` and it should work.

**Comment by astevko** [comment]
for the record
`python3 -m pip install python-dotenv
`
does the trick.
