### ISSUE TITLE
pkg_resources.DistributionNotFound: click>=3.0

### ISSUE THREAD

**Issue by philippeluickx** [theskumar/python-dotenv#4]
Trying to run dotenv list (or any other command), getting this error message

Traceback (most recent call last):
  File "/foobar/bin/dotenv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/foobar/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
  File "/foobar/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
  File "/foobar/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: click>=3.0

**Comment by philippeluickx** [comment]
pip install --upgrade setuptools

Did the trick...

**Comment by theskumar** [comment]
Everything works just fine here: https://travis-ci.org/theskumar/python-dotenv/jobs/52423460#L100

Probably it's just because you had older version of setuptools. Can't say for sure. Reopen if you face similar issue again. I'll try to update docs or fix the issue.

**Comment by philippeluickx** [comment]
It's not something that can be put in requirements.txt it seems. Not really an issue on the part of the library either.
People with similar issues can find the ticket I hope. No need to reopen in my opinion.

**Comment by theskumar** [comment]
:+1:
