### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by tchia04** [theskumar/python-dotenv#44]
I am using 
python-dotenv (0.6.1)

content of my .env file

cat .env
DOMAIN="example.org"
a="b"

<pre>
tonychia@Tonys-MacBook-Pro ~ $ dotenv list
Traceback (most recent call last):
  File "/usr/local/bin/dotenv", line 11, in <module>
    sys.exit(cli.cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/dotenv/cli.py", line 29, in list
    for k, v in dotenv_as_dict:
ValueError: too many values to unpack
</pre>

**Comment by theskumar** [comment]
@tchia04 I've released v0.6.2, please try and let me know if it fixes the issue. Thanks to @ticosax we already had a fix for it in `master` branch. 

https://github.com/theskumar/python-dotenv/commit/8e6df7b1a889da7840efded9e34bd6c118cc3bf3
