### ISSUE TITLE
Error when installing dotenv with miniconda

### ISSUE THREAD

**Issue by fdb** [theskumar/python-dotenv#458]
While installing dotenv I suddenly get the following error:

```bash
(workshop) fdb@mba % pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      /Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [17 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/private/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/pip-wheel-dpzp0d4p/distribute_69535f81f44b4726b6eebed755846be1/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/private/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/pip-wheel-dpzp0d4p/distribute_69535f81f44b4726b6eebed755846be1/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/private/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/pip-wheel-dpzp0d4p/distribute_69535f81f44b4726b6eebed755846be1/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/private/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/pip-wheel-dpzp0d4p/distribute_69535f81f44b4726b6eebed755846be1/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/private/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/pip-wheel-dpzp0d4p/distribute_69535f81f44b4726b6eebed755846be1/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/private/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/pip-wheel-dpzp0d4p/distribute_69535f81f44b4726b6eebed755846be1/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/fdb/miniconda3/envs/workshop/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/tmpapjcxb7v', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/pip-install-qqfwsqr_/dotenv_2eedba3a0a154cbc96f8e17fbeb1b5e9/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/pkg_resources/__init__.py", line 815, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/pkg_resources/__init__.py", line 851, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1123, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
          return fetch_build_egg(self, req)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/fdb/miniconda3/envs/workshop/lib/python3.11/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/fdb/miniconda3/envs/workshop/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/09/wr82kbm90l15_22czr3mjs240000gn/T/tmpapjcxb7v', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

MacBook Air M1 running Ventura 13.3.1.

```
(workshop fdb@mba % which python
/Users/fdb/miniconda3/bin/python
(workshop) fdb@mba % python -V
Python 3.11.3
```

**Comment by fdb** [comment]
My mistake — I needed to install `python-dotenv`. That works without issues.
