### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by fengerzh** [theskumar/python-dotenv#462]
Environment:

```
$ python --version                                                                                                                                     (pypy39) 
Python 3.9.16 | packaged by conda-forge | (feeb267e, Jan 18 2023, 16:17:35)
[PyPy 7.3.11 with GCC Clang 14.0.6]
```

install command:

```
$ pip install dotenv                                                                                                                                   (pypy39) 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting dotenv
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e2/46/3754073706e31670eed18bfa8a879305b56a471db15f20523c2427b10078/dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            /opt/miniconda3/envs/pypy39/lib/pypy3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
              warnings.warn(msg)
            /opt/miniconda3/envs/pypy39/lib/pypy3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
              warnings.warn(msg)
            usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
               or: setup.py --help [cmd1 cmd2 ...]
               or: setup.py --help-commands
               or: setup.py cmd --help
      
            error: invalid command 'egg_info'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/miniconda3/envs/pypy39/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/tmpklub4m9m', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/pip-install-_92hiaev/dotenv_b88b2c7b34c74849898a0cccc9ae71ba/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
          dist = best[req.key] = env.best_match(
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
          return installer(requirement)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/opt/miniconda3/envs/pypy39/lib/pypy3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/opt/miniconda3/envs/pypy39/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/kk/yj3hfw3n2r94r459vvddjpkm0000gn/T/tmpklub4m9m', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jbachus** [comment]
I know it's easy to confuse since I've done it myself, but the package should be `python-dotenv` not just `dotenv` for your pip install.
