### ISSUE TITLE
couldn't install with pip

### ISSUE THREAD

**Issue by abhinavpatel0** [theskumar/python-dotenv#519]
pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [17 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 14, in <module>
          File "C:\Users\hp\AppData\Local\Temp\pip-wheel-s6n8tgaz\distribute_dfd06ad55c864c3b8de15c96bbc6d805\setuptools\__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "C:\Users\hp\AppData\Local\Temp\pip-wheel-s6n8tgaz\distribute_dfd06ad55c864c3b8de15c96bbc6d805\setuptools\extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "C:\Users\hp\AppData\Local\Temp\pip-wheel-s6n8tgaz\distribute_dfd06ad55c864c3b8de15c96bbc6d805\setuptools\dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "C:\Users\hp\AppData\Local\Temp\pip-wheel-s6n8tgaz\distribute_dfd06ad55c864c3b8de15c96bbc6d805\setuptools\command\__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "C:\Users\hp\AppData\Local\Temp\pip-wheel-s6n8tgaz\distribute_dfd06ad55c864c3b8de15c96bbc6d805\setuptools\command\install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "C:\Users\hp\AppData\Local\Temp\pip-wheel-s6n8tgaz\distribute_dfd06ad55c864c3b8de15c96bbc6d805\pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\hp\\AppData\\Local\\Temp\\tmpjy2zyo7n', '--quiet', 'distribute']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hp\AppData\Local\Temp\pip-install-o83jhvkr\dotenv_099ce25125874c0da71af8e7582d4160\setup.py", line 13, in <module>
          setup(name='dotenv',
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\hp\\AppData\\Local\\Temp\\tmpjy2zyo7n', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Bajron** [comment]
Note that `dotenv` is a different package. This github project is about `python-dotenv`.
It is a common confusion. There were some trials to resolve this in the following issue: https://github.com/theskumar/python-dotenv/issues/448

**Comment by abhinavpatel0** [comment]
thank you so much i got it solved
