### ISSUE TITLE
pip report will not output to a file

### ISSUE THREAD

**Issue by idrinkdeodorant** [theskumar/python-dotenv#537]
[python-dotenv_pip_report.json](https://github.com/user-attachments/files/17471601/python-dotenv_pip_report.json)
In Windows 11 Command Prompt or PowerShell, if I do:
`pip install python-dotenv --report -`
... a valid JSON is output to the terminal (see attached).

If I do:
`pip install python-dotenv --report - > test.json`
... I get these errors

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_internal\commands\install.py", line 386, in run
    print_json(data=report.to_dict())
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\__init__.py", line 106, in print_json
    get_console().print_json(
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\console.py", line 1782, in print_json
    self.print(json_renderable, soft_wrap=True)
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\console.py", line 1673, in print
    with self:
         ^^^^
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\console.py", line 865, in __exit__
    self._exit_buffer()
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\console.py", line 2027, in _check_buffer
    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
  File "C:\git\test_project\python\env\Lib\site-packages\pip\_vendor\rich\_win32_console.py", line 403, in write_text
    self.write(text)
  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1861-1863: character maps to <undefined>
```

No other package results in this issue when using `pip --report`.

Thanks.

**Comment by idrinkdeodorant** [comment]
Closing this.
